# Wi-Fi configuration
CONFIG_WIFI=y
CONFIG_WIFI_OFFLOAD=y  # For Full-MAC Wi-Fi devices
CONFIG_WIFI_USAGE_MODE_STA=y  # Wi-Fi interface as station

# Networking
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_LOG=y
CONFIG_NET_SHELL=y

# Shell support
CONFIG_SHELL=y
