CONFIG_CPP=y
CONFIG_NEWLIB_LIBC=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_HTS221=y
CONFIG_IIS2MDC=y
CONFIG_ISM330DHCX=y
CONFIG_LPS22HH=y
CONFIG_LPS22HH_TRIGGER_GLOBAL_THREAD=y
CONFIG_GPIO=y

# VL53L5CX Time-of-Flight sensor (disabled for now)
# CONFIG_VL53L5CX=y
# CONFIG_VL53L5CX_TRIGGER=y

CONFIG_FPU=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
